// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALrMiZL7dOLl4ksrDtfA4uheb966JcB8',
    appId: '1:68228839783:web:acf286c03bd5fadcc157c2',
    messagingSenderId: '68228839783',
    projectId: 'abdulahsidikuts',
    authDomain: 'abdulahsidikuts.firebaseapp.com',
    storageBucket: 'abdulahsidikuts.appspot.com',
    measurementId: 'G-WLFRP19GDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzPSYRLFe2WptRjtL3R4_esyzPzzZDR5o',
    appId: '1:68228839783:android:4b2e456a7852a9b6c157c2',
    messagingSenderId: '68228839783',
    projectId: 'abdulahsidikuts',
    storageBucket: 'abdulahsidikuts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBs6J_SGdjJQohqE3knXm17-Hqft-gCM',
    appId: '1:68228839783:ios:4a3c2310d67b1e46c157c2',
    messagingSenderId: '68228839783',
    projectId: 'abdulahsidikuts',
    storageBucket: 'abdulahsidikuts.appspot.com',
    androidClientId: '68228839783-hr6ttnesh967bb9ret89bt2bipjjbamg.apps.googleusercontent.com',
    iosClientId: '68228839783-ik5o35trut9p0i8euhilapjnf5ufrrgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.abdullahsidikUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBs6J_SGdjJQohqE3knXm17-Hqft-gCM',
    appId: '1:68228839783:ios:f4c6d7a22cb367f5c157c2',
    messagingSenderId: '68228839783',
    projectId: 'abdulahsidikuts',
    storageBucket: 'abdulahsidikuts.appspot.com',
    androidClientId: '68228839783-hr6ttnesh967bb9ret89bt2bipjjbamg.apps.googleusercontent.com',
    iosClientId: '68228839783-bqtu1k8s71r426su6in2l6gdmio1hdfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.abdullahsidikUts.RunnerTests',
  );
}
